import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// dynamic imports of the components
const Landing_footer = dynamic(() =>
  import("../components/Landing_footer/Landing_footer")
);
const Navbar = dynamic(() => 
  import("../components/Landing_navbar/Landing_navbar")
);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        {children}
        <Landing_footer/>
      </body>
    </html>
  );
}
