"use client"
import styles from './Landing_faq.module.css'
import Image from 'next/image'
import { useState } from 'react'
import { IoIosArrowDown, IoIosArrowUp } from 'react-icons/io'

const Question = ({ question, answer, color }) => {
  const [open, setOpen] = useState(false);

  return (
    <div
      className={`${styles.question_container} ${
        color % 2 === 1 ? styles.question_green_container : ''
      }`}
    >
      {/* HEADER (click only here) */}
      <button
        type="button"
        className={styles.question_header}
        onClick={() => setOpen((prev) => !prev)}
      >
        <p>{question}</p>
        {open ? <IoIosArrowUp /> : <IoIosArrowDown />}
      </button>

      {/* ANSWER */}
      {open && (
        <div className={styles.help_answer}>
          <p>{answer}</p>
        </div>
      )}
    </div>
  );
};


const Landing_faq = () => {
  const questionsData = [
  {
    question: 'How much time does my staff need to spend on this?',
    answer:
      'Almost none. The Growth Engine is designed to work in the background. Your reception only gets involved when a patient is already pre-qualified and ready to be booked into the calendar.',
  },
  {
    question: 'Do I need to replace my current booking software?',
    answer:
      'No. Our system acts as a bridge and integrates with most major dental practice management softwares. We enhance your current workflow, not replace it.',
  },
  {
    question: 'How soon will we see an increase in bookings?',
    answer:
      'Most clinics see a 30–45% increase in lead response rates within the first 14 days. Since the automation is instant, the leak in your budget is plugged the moment we go live.',
  },
  {
    question: 'Are we locked into long-term contracts?',
    answer:
      'No. We believe in results, not hostages. We offer flexible terms because we are confident that the ROI generated by the Growth Engine will make you want to stay with us long-term.',
  },
];

  return (
    <div className={styles.help_container}>
      <div className={styles.help_content}>
      <div className={styles.help_question_title}>
        <h1>Find a question</h1>

        {questionsData.map((q, i) => (
          <Question
            key={i}
            question={q.question}
            answer={q.answer}
            color={i}
          />
        ))}
      </div>

      <div className={styles.help_img_container}>
        <Image
          width={300}
          height={400}
          src="./faq.jpg"
          alt="help"
          className={styles.help_img_appear}
        />
      </div>
    </div>
    </div>
  );
};

export default Landing_faq