"use client";

import styles from './Landing_faq.module.css';
import Image from 'next/image';
import { useState } from 'react';
import { IoIosArrowDown } from 'react-icons/io';
import faq_img from "../../../public/images/faq.jpg";
import { motion, AnimatePresence } from 'framer-motion';
import { track } from "@vercel/analytics"

//motion
const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.15,
      delayChildren: 0.2,
    },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, ease: "easeOut" },
  },
};

const Question = ({ question, answer, index }) => {
  const [open, setOpen] = useState(false);


const handleQuestionClick = () => {
  setOpen((prev) => !prev);
  track(question, {location: "FAQ_Section"});
}

  return (
    <motion.div
      variants={itemVariants}
      className={`${styles.question_container} ${
        index % 2 === 1 ? styles.question_green_container : ''
      }`}
    >
      <button
        type="button"
        className={styles.question_header}
        onClick={() => handleQuestionClick}
      >
        <p>{question}</p>
        <motion.div
          animate={{ rotate: open ? 180 : 0 }}
          transition={{ duration: 0.3 }}
        >
          <IoIosArrowDown />
        </motion.div>
      </button>

      {/* 2. AnimatePresence handles the mounting/unmounting animation */}
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            style={{ overflow: "hidden" }} // Prevents text pop-in
          >
            <div className={styles.help_answer}>
              <p>{answer}</p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

const Landing_faq = () => {
  const questionsData = [
    {
      question: 'How much time does my staff need to spend on this?',
      answer: 'Almost none. The Growth Engine is designed to work in the background. Your reception only gets involved when a patient is already pre-qualified and ready to be booked into the calendar.',
    },
    {
      question: 'Do I need to replace my current booking software?',
      answer: 'No. Our system acts as a bridge and integrates with most major dental practice management softwares. We enhance your current workflow, not replace it.',
    },
    {
      question: 'How soon will we see an increase in bookings?',
      answer: 'Most clinics see a 30–45% increase in lead response rates within the first 14 days. Since the automation is instant, the leak in your budget is plugged the moment we go live.',
    },
    {
      question: 'Are we locked into long-term contracts?',
      answer: 'No. We believe in results, not hostages. We offer flexible terms because we are confident that the ROI generated by the Growth Engine will make you want to stay with us long-term.',
    },
  ];

  return (
    <div className={styles.help_container}>
      <div className={styles.help_content}>
        
        {/* 3. Wrap the questions in a motion.div to trigger the stagger */}
        <motion.div 
          className={styles.help_question_title}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.2 }}
          variants={containerVariants}
        >
          <motion.h1 variants={itemVariants}>
            Find a question
          </motion.h1>

          {questionsData.map((q, i) => (
            <Question
              key={i}
              question={q.question}
              answer={q.answer}
              index={i}
            />
          ))}
        </motion.div>

        <motion.div 
          className={styles.help_img_container}
          initial={{ opacity: 0, x: 30 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8, delay: 0.5 }}
        >
          <Image
            width={300}
            height={400}
            src={faq_img}
            alt="help"
            className={styles.help_img_appear}
          />
        </motion.div>
      </div>
    </div>
  );
};

export default Landing_faq;